typography_spectrum: 0.9297229761723429
color:
  brandStrength: 0.9754471776541322
  lightness: 0.3190731117501855
  saturation: 0.9432248477824032
  rhythmicContrast: 0.3812689664773643
  brandColors:
    - '#F4F2EE'
    - '#FAF8F2'
    - '#FDFCF9'
    - '#EFECE9'
    - '#FFFFFF'
github: true
layout_spectrum: 0.5800841371528804
analytics:
  google: UA-100593811-1
author:
  name: '@copyright'
  email: adrian@bbiab.com
  url: 'https://thegrid.ai/store/copyright'
name: store
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: speakeasy
    url: 'https://thegrid.ai/bar'
    type: external
title: the old curiosity store
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/1acafb9b-b379-4d75-a6ed-c65caf46b174.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/1acafb9b-b379-4d75-a6ed-c65caf46b174.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'all hand made with love.. ~ opening hours : 24/7'
url: 'http://store.abc-xyz.us/'
purpose:
  - type: external
    url: 'https://abc-xyz.us'
    label: abc.. to xyz
