layout_spectrum: 0.18428669204668022
typography_spectrum: 0.18034361639023194
color:
  brandStrength: 0.6574450246261268
  lightness: 0.6266122424346164
  saturation: 0.16460951516201885
  rhythmicContrast: 0.1061225614367551
  brandColors:
    - '#F4F2EE'
    - '#FAF8F2'
    - '#FDFCF9'
    - '#EFECE9'
    - '#FFFFFF'
github: true
analytics:
  google: UA-100593811-1
author:
  name: '@copyright'
  email: adrian@bbiab.com
  url: 'https://thegrid.ai/store/copyright'
name: store
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: the old curiosity store
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/1acafb9b-b379-4d75-a6ed-c65caf46b174.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/1acafb9b-b379-4d75-a6ed-c65caf46b174.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'all hand made with love.. ~ opening hours : 24/7'
url: 'http://store.abc-xyz.us/'
purpose:
  - type: external
    url: 'https://abc-xyz.us'
    label: abc.. to xyz
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/079c80c9-4632-4078-8e89-21d109e2a2a9.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d8e062f5-7236-4252-8761-03094a3f7ec6.png
